### PR TITLE
Add Demo 4 - Using tablist and tabpanel attributes

### PR DESCRIPTION
**Pull request by gemmaleigh**
- Create test case 4
- Add demo JS and scss

Testing the accordion pattern described here:
https://www.w3.org/TR/wai-aria-practices/#accordion

This demo aims to use the correct ARIA roles states and properties
mentioned in the link above, but does not have full keyboard navigation.

### CODE REVIEW

**Comment by aduggin** [comment]
The pattern is incomplete without the keyboard interaction - is this something that you can add?

@LjWatson - can you confirm if the keyboard interaction needs to be added before testing the WAI-ARIA version of the pattern?

**Comment by gemmaleigh** [comment]
Hi @aduggin the keyboard interation is as follows:

When focus is on an accordion header, pressing the Tab key moves focus in the following manner:
- When the corresponding panel is expanded (its aria-expanded state is 'true'), then focus moves to the first focusable element in the panel.
- If the panel is collapsed (its aria-expanded state is 'false' or missing), OR, when the last interactive element of a panel is reached, the next Tab key press moves focus as follows:
- If a subsequent accordion panel is already expanded, focus moves to the first focusable element in this subsequent panel.
- If no subsequent accordion panel is expanded, focus moves to the first focusable element outside the accordion component.
- Enter/Space - When focus is on an accordion header, pressing Enter/Space toggles the expansion of the corresponding panel.
  If collapsed, the panel is expanded, and its aria-expanded state is set to 'true'.
  If expanded, the panel is collapsed and its aria-expanded state is set to 'false'.
- Shift+Tab - Generally the reverse of Tab.

From here: https://www.w3.org/TR/wai-aria-practices/#accordion

It doesn't yet have the _full_ keyboard interaction, for arrow keys and Home buttons (detailed below). I'd like to find out if this is a viable pattern before adding this further interaction.
- Left arrow
  When focus is on the accordion header, a press of up/left arrow keys moves focus to the previous logical accordion header.
  When focus reaches the first header, further up/left arrow key presses optionally wrap to the first header.
- Right arrow
  When focus is on the accordion header, a press of down/right moves focus to the next logical accordion header.
  When focus reaches the last header, further down/right arrow key presses optionally wrap to the first header
- Up arrow - behaves the same as left arrow
- Down arrow - behaves the same as right arrow
- End - When focus is on the accordion header, an End key press moves focus to the last accordion header.
- Home - When focus is on the accordion header, a Home key press moves focus to the first accordion header.

**Comment by LJWatson** [comment]
@gemmaleigh 
I don't think this is a pattern worth pursuing, despite the fact the ARIA APG recommends it. Keeping the interaction simple seems like a better option for our target audience.

There is also the fact that when the tablist role is used, it automatically kicks screen readers into application mode (so keystrokes are passed back through to the browser instead of being intercepted by the screen reader). Unless keyboard interaction is provided through scripting, this design pattern will be unusable with many screen readers.

**Comment by gemmaleigh** [comment]
@LjWatson @aduggin, thanks - I'll close this PR.

**Pull request closed without merging**
